services:
  # Base de données MySQL
  db: 
    image: mysql:latest
    restart: always
    container_name: db_mysql2
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports: 
      - "3306:3306"
    volumes: 
      - local_mysqldata:/var/lib/mysql
    networks:
      - app-network

  # Interface phpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin2
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - phpmyadmin-data:/sessions
    networks:
      - app-network

  # Service Backend (Spring Boot)
  backend:
    build: ./back_employee
    container_name: backend_service
    ports:
      - "8081:8080" # Le backend écoute sur le port 8080, mappé ici sur 8081
    networks:
      - app-network
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

  # Service Frontend (React)
  frontend:
    build: ./front_employee
    container_name: frontend_service
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

# Volumes pour la persistance des données
volumes:
  local_mysqldata:
  phpmyadmin-data:

# Réseau commun pour les services
networks:
  app-network:
