services:
  db: 
    image: mysql:latest
    restart: always
    container_name: db_mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: default
    ports: 
      - "3306:3306"
    volumes: 
      - local_mysqldata:/var/lib/mysql
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    volumes: 
      - phpmyadmin-data:/sessions
    networks:
    - mysql-phpmyadmin

volumes:
  local_mysqldata:
  phpmyadmin-data:

networks:
  mysql-phpmyadmin:
